@startuml триада-внешняя
skinparam defaultFontSize 15
scale max 600 width

<style>
node {
    FontSize 25
}
cloud {
    FontSize 25
}
queue {
    FontSize 25
}
</style>

node состояние
note right
    физическое воплощение на "столе"
end note

cloud объяснение
note right
    ментальная трактовка в "голове"
end note

queue воздействие
note right
    виртуальный эффект в "руке"
end note

состояние -[hidden]-> объяснение
объяснение -[hidden]-> воздействие
@enduml

@startuml триада-внутренняя
skinparam defaultTextAlignment center
skinparam defaultFontSize 15
scale max 600 width

<style>
stack {
    FontSize 25
}
folder {
    FontSize 25
}
person {
    FontSize 25
}
</style>

stack "  мир  " as world
note right
    Независимо **существует** в рамках заданного **сеттинга**.
    Может оказывать влияние на сюжет и персонажей.
    Генерирует **риски**.
end note

folder " сюжет" as gamelang
note right
    Независимо **развивается** в рамках заданного **лора**.
    Может оказывать влияние на персонажей и мир.
    Генерирует **неопределенности**.
end note

person "персонаж" as character
note right
    Независимо **действует** в рамках заданной **перспективы**.
    Может оказывать влияние на сюжет и мир.
    Снимает риски и 
end note

world -[hidden]-> gamelang
gamelang -[hidden]-> character
@enduml

@startuml цикл-существования
skinparam actorStyle hollow
skinparam defaultFontSize 15
skinparam defaultTextAlignment center
skinparam nodesep 50
skinparam ranksep 10
scale max 600 width

<style>
stack {
    FontSize 25
}
</style>

stack "  мир  " as main

cloud expl [
    <size:20>объяснение</size>
]
queue infl [
    <size:20>воздействие</size>
]
node impl [
    <size:20>состояние</size>
]

entity characterAgent [
    <size:20>мастер</size>
    ..
    вскрывает
    **риски**

]
control avatarAgent [
    <size:20>движок</size>
    ..
    порождает
    **риски**

]
actor player [
    <size:20>игрок</size>
    ..
    учитывает
    **риски**
]

main ~[hidden]u~ impl: -
main ~[hidden]d~ expl
main ~[hidden]d~ infl

main ~[hidden]u~ avatarAgent
main ~[hidden]d~ player
main ~[hidden]u~ characterAgent

impl ~[hidden]r~ avatarAgent
avatarAgent ~[hidden]d~ infl

infl ~[hidden]d~ player
expl ~[hidden]d~ player

expl ~[hidden]u~ characterAgent
characterAgent ~[hidden]r~ impl

impl -d-> expl
expl -r-> infl
infl -u-> impl
@enduml

@startuml цикл-развития
skinparam actorStyle hollow
skinparam defaultFontSize 15
skinparam defaultTextAlignment center
skinparam nodesep 50
skinparam ranksep 10
scale max 600 width

<style>
folder {
    FontSize 25
}
</style>

folder " сюжет" as main

cloud expl [
    <size:20>объяснение</size>
]
queue infl [
    <size:20>воздействие</size>
]
node impl [
    <size:20>состояние</size>
]

entity characterAgent [
    <size:20>мастер</size>
    ..
    порождает
    **неопределенности**

]
control avatarAgent [
    <size:20>движок</size>
    ..
    вскрывает
    **неопределенности**

]
actor player [
    <size:20>игрок</size>
    ..
    учитывает
    **неопределенности**
]

main ~[hidden]u~ impl: -
main ~[hidden]d~ expl
main ~[hidden]d~ infl

main ~[hidden]u~ avatarAgent
main ~[hidden]d~ player
main ~[hidden]u~ characterAgent

impl ~[hidden]r~ avatarAgent
avatarAgent ~[hidden]d~ infl

infl ~[hidden]d~ player
expl ~[hidden]d~ player

expl ~[hidden]u~ characterAgent
characterAgent ~[hidden]r~ impl

impl -d-> expl
expl -r-> infl
infl -u-> impl
@enduml

@startuml цикл-деятельности
skinparam actorStyle hollow
skinparam defaultFontSize 15
skinparam defaultTextAlignment center
skinparam nodesep 50
skinparam ranksep 10
scale max 600 width

<style>
person {
    FontSize 22
}
</style>

person "персонаж" as main

cloud expl [
    <size:20>объяснение</size>
]
queue infl [
    <size:20>воздействие</size>
]
node impl [
    <size:20>состояние</size>
]

entity characterAgent [
    <size:20>мастер</size>
    ..
    ???
    **издержки**

]
control avatarAgent [
    <size:20>движок</size>
    ..
    ???
    **издержки**
    
]
actor player [
    <size:20>игрок</size>
    ..
    порождает
    **издержки**
]

impl -d-> expl
expl -r-> infl
infl -u-> impl

main ~[hidden]u~ impl: -
main ~[hidden]d~ expl
main ~[hidden]d~ infl

main ~[hidden]u~ avatarAgent
main ~[hidden]d~ player
main ~[hidden]u~ characterAgent

impl ~[hidden]r~ avatarAgent
avatarAgent ~[hidden]d~ infl

infl ~[hidden]d~ player
expl ~[hidden]d~ player

expl ~[hidden]u~ characterAgent
characterAgent ~[hidden]r~ impl
@enduml

@startuml цикл-обобщенный
skinparam nodesep 75
skinparam ranksep 40
skinparam defaultFontSize 15
skinparam defaultTextAlignment center
skinparam actorStyle hollow
scale max 600 width

<style>
control {
    FontSize 30
}
entity {
    FontSize 30
}
actor {
    FontSize 30
}
cloud {
    FontSize 30
}
queue {
    FontSize 30
}
node {
    FontSize 30
}
title {
    FontStyle plain
}
</style>

title Механики исполняются в рамках правил

node "состояние" as impl
cloud "объяснение" as expl
queue "воздействие" as infl

entity characterAgent [
    мастер
    ....
    <size:15>отвечает за **трансдукцию**</size>
    <size:15>объяснения с учётом</size>
    <size:15>нового состояния</size>

]

actor player [
    игрок
    ....
    <size:15>отвечает за **трансакцию**</size>
    <size:15>воздействия с учётом</size>
    <size:15>нового объяснения</size>
]

control avatarAgent [
    движок
    ....
    <size:15>отвечает за **трансформацию**</size>
    <size:15>состояния с учётом</size>
    <size:15>нового воздействия</size>

]

impl ~[hidden]r~ avatarAgent
avatarAgent ~[hidden]d~ infl

infl ~[hidden]d~ player
expl ~[hidden]d~ player

expl ~[hidden]u~ characterAgent
characterAgent ~[hidden]r~ impl

impl -d-> expl
expl -r-> infl: <size:35>правила</size>\t\n\n
infl -u-> impl
@enduml

@startuml спираль-обобщенная
skinparam nodesep 100
skinparam ranksep 50
skinparam defaultFontSize 20
scale max 1200 width

rectangle "0000000000000000000" as stub1
hidden stub1
rectangle "0000000000000000000" as stub2
hidden stub2

node "состояние<sub> <U+3007></sub>" as impl0
cloud "объяснение<sub> <U+3007></sub>" as expl0
queue "воздействие<sub> <U+3007></sub>" as infl0

node "состояние<sub> 1</sub>" as impl1
cloud "объяснение<sub> 1</sub>" as expl1
queue "              ...             " as infl1

node "состояние<sub> k</sub>" as impl2
cloud "объяснение<sub> k</sub>" as expl2
queue "воздействие<sub> <U+2205></sub>" as infl2

node "состояние<sub> <U+2205></sub>" as impl3
cloud "объяснение<sub> <U+2205></sub>" as expl3

label legend [
    <size:20><U+3007> - начальное</size>
    <size:20><U+2205> - финальное</size>
]

stub1 ~d~> infl0
stub1 -r-> impl0

impl0 -d-> expl0: ТД<sub><U+3007></sub>
expl0 -r-> infl0: ТА<sub><U+3007></sub>

impl0 ~d~> impl1
infl0 -r-> impl1: ТФ<sub>1</sub>

expl0 ~d~> expl1
impl1 -d-> expl1: ТД<sub>1</sub>

infl0 ~d~> infl1
expl1 -r-> infl1: ТА<sub>1</sub>

impl1 ~d~> impl2
infl1 -r-> impl2: ТФ<sub>k</sub>

expl1 ~d~> expl2
impl2 -d-> expl2: ТД<sub>k</sub>

infl1 ~d~> infl2
expl2 -r-> infl2: ТА<sub>k</sub>

impl2 ~d~> impl3
infl2 -r-> impl3: ТФ<sub><U+2205></sub>

expl2 ~d~> expl3
impl3 -d-> expl3: ТД<sub><U+2205></sub>

infl2 ~d~> stub2
expl3 -r-> stub2

stub2 -r-> legend
@enduml

@startuml трансформация
skinparam nodesep 100
skinparam ranksep 100
skinparam defaultFontSize 25
scale max 600 width

<style>
title {
    FontSize 15
    FontStyle plain
}
caption {
    FontSize 15
}
</style>

node "состояние<sub> k-1</sub>" as impl1
queue "воздействие<sub> k</sub>" as p
node "состояние<sub> k</sub>" as impl2

impl1 ~d~> impl2
p -r-> impl2: ТФ<sub>k</sub>\n\n

caption С<sub> k</sub> = ТФ (С<sub>k-1</sub>, В<sub>k</sub>)
@enduml

@startuml трансдукция
skinparam nodesep 100
skinparam ranksep 100
skinparam defaultFontSize 25
scale max 600 width

<style>
title {
    FontSize 15
    FontStyle plain
}
caption {
    FontSize 15
}
</style>

cloud "объяснение<sub> k-1</sub>" as expl1
node "состояние<sub> k</sub>" as impl
cloud "объяснение<sub> k</sub>" as expl2

expl1 ~d~> expl2
impl -r-> expl2: ТД<sub>k</sub>\n\n

caption О<sub>k</sub> = ТД (О<sub>k-1</sub>, С<sub>k</sub>)
@enduml

@startuml трансакция
skinparam nodesep 100
skinparam ranksep 100
skinparam defaultFontSize 25
scale max 600 width

<style>
title {
    FontSize 15
    FontStyle plain
}
caption {
    FontSize 15
}
</style>

queue "воздействие<sub> k-1</sub>" as infl1
cloud "объяснение<sub> k</sub>" as expl
queue "воздействие<sub> k</sub>" as infl2

infl1 ~d~> infl2
expl -r-> infl2: ТА<sub>k</sub>\n\n

caption В<sub>k</sub> = ТА (В<sub>k-1</sub>, О<sub>k</sub>)
@enduml

@startgantt триада-времен
skinparam defaultFontSize 30
scale max 1200 width

<style>
ganttDiagram {
    timeline {
        LineColor transparent
        FontColor transparent
    }
    task {
        LineColor transparent
    }
}
</style>

[время разработки игры] as [dt] requires 8 days
[время игровой партии] as [pt] requires 8 days
[время обмена впечатлениями] as [st] requires 10 days

[dt] -> [pt]
[pt] -> [st]
@endgantt
