@startuml filled-player
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 150
skinparam nodesep 50

$empty_grid_3x1()
$join_grid_3x1("hidden")
@enduml

@startuml filled-characterAgent-and-filled-avatarAgent
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 30
skinparam nodesep 50

$fill_character_agent()
$empty_grid_3x1()
$fill_avatar_agent()
$join_grid_5x1("hidden")
@enduml

@startuml outlined-character-and-outlined-avatar
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 30
skinparam nodesep 50

$fill_character_agent()
$draft_protocol(character)
$fill_players()
$draft_protocol(avatar)
$fill_avatar_agent()
$join_grid_5x1("hidden")
@enduml

@startuml filled-character-and-outlined-avatar
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 30
skinparam nodesep 50

$fill_character_agent()
$fill_characters()
$fill_players()
$draft_protocol(avatar)
$fill_avatar_agent()
$join_grid_5x1("hidden")
@enduml

@startuml outlined-character-and-filled-avatar
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 25
skinparam nodesep 50

$fill_character_agent()
$draft_protocol(character)
$fill_players()
$fill_avatars()
$fill_avatar_agent()
$join_grid_5x1("hidden")
@enduml

@startuml filled-characters-and-filled-avatars
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 25
skinparam nodesep 50

$fill_grid_5x1(N)
$join_grid_5x1("hidden")
@enduml
