@startuml player-with-axes
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 20
skinparam nodesep 1

<style>
  .axis {
    FontColor: black;
  }
</style>

$iconify_players()

$fill_axes()
$empty_axes()
$join_axes_3x3(hidden, hidden)
@enduml

@startmindmap axis-x-with-clarifications-en
!include lib/game.puml!core
!include lib/i18n.puml!en

<style>
node {
  MaximumWidth 600
  Padding 5
  Margin 10
}
.term {
  FontSize 30
  LineColor DimGrey
  LineThickness 0.5
  BackgroundColor transparent
}
.defn {
  FontSize 20
  BackgroundColor transparent
  LineColor transparent
}
</style>

+ $translate(gamelang2) <<term>>
++ $translate(idea), $translate(model), $translate(explanation) <<defn>>
++ $translate(grammar), $translate(query), $translate(meaning) <<defn>>
++ $translate(intention), $translate(cause), $translate(concern) <<defn>>

+ $translate(gameplay2) <<term>>
++ $translate(world), $translate(state), $translate(observation) <<defn>>
++ $translate(interface), $translate(command), $translate(effect) <<defn>>
++ $translate(action), $translate(resource), $translate(inertia) <<defn>>
@endmindmap

@startmindmap axis-x-with-clarifications-ru
!include lib/game.puml!core
!include lib/i18n.puml!ru

<style>
node {
  MaximumWidth 600
  Padding 5
  Margin 10
}
.term {
  FontSize 30
  LineColor DimGrey
  LineThickness 0.5
  BackgroundColor transparent
}
.defn {
  FontSize 20
  BackgroundColor transparent
  LineColor transparent
}
</style>

+ $translate(gamelang2) <<term>>
++ $translate(idea), $translate(model), $translate(explanation) <<defn>>
++ $translate(grammar), $translate(query), $translate(meaning) <<defn>>
++ $translate(intention), $translate(cause), $translate(concern) <<defn>>

+ $translate(gameplay2) <<term>>
++ $translate(world), $translate(state), $translate(observation) <<defn>>
++ $translate(interface), $translate(command), $translate(effect) <<defn>>
++ $translate(action), $translate(resource), $translate(inertia) <<defn>>
@endmindmap

@startmindmap axis-y-with-clarifications-en
!include lib/game.puml!core
!include lib/i18n.puml!en

<style>
node {
  MaximumWidth 600
  Padding 5
  Margin 10
}
.term {
  FontSize 30
  LineColor DimGrey
  LineThickness 0.5
  BackgroundColor transparent
}
.defn {
  FontSize 20
  BackgroundColor transparent
  LineColor transparent
}
</style>

+ $translate(gameloop2) <<term>>
++ $translate(logic), $translate(judgment), $translate(rationality) <<defn>>
++ $translate(rule), $translate(alienation), $translate(authenticity) <<defn>>
++ $translate(cyclicality), $translate(typicality), $translate(isolation) <<defn>>

+ $translate(gamefeel2) <<term>>
++ $translate(intuition), $translate(feeling), $translate(emotionality) <<defn>>
++ $translate(inspiration), $translate(participation), $translate(subjectivity) <<defn>>
++ $translate(finiteness), $translate(uniqueness), $translate(interactivity) <<defn>>
@endmindmap

@startmindmap axis-y-with-clarifications-ru
!include lib/game.puml!core
!include lib/i18n.puml!ru

<style>
node {
  MaximumWidth 600
  Padding 5
  Margin 10
}
.term {
  FontSize 30
  LineColor DimGrey
  LineThickness 0.5
  BackgroundColor transparent
}
.defn {
  FontSize 20
  BackgroundColor transparent
  LineColor transparent
}
</style>

+ $translate(gameloop2) <<term>>
++ $translate(logic), $translate(judgment), $translate(rationality) <<defn>>
++ $translate(rule), $translate(alienation), $translate(authenticity) <<defn>>
++ $translate(cyclicality), $translate(typicality), $translate(isolation) <<defn>>

+ $translate(gamefeel2) <<term>>
++ $translate(intuition), $translate(feeling), $translate(emotionality) <<defn>>
++ $translate(inspiration), $translate(participation), $translate(subjectivity) <<defn>>
++ $translate(finiteness), $translate(uniqueness), $translate(interactivity) <<defn>>
@endmindmap

@startuml matrix-with-axes
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 40
skinparam nodesep 1

<style>
  label {
    FontSize: 30;
  }
</style>

$iconify_players()

$fill_axes()
$empty_axes()
$join_axes_3x3(hidden, hidden)

$fill_matrix(1)
$join_matrix_3x3()
@enduml

@startuml matrix-with-protocols-singular
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 20
skinparam nodesep 40

<style>
  .matrix {
    FontSize: 30;
    FontColor: Grey;
  }
</style>

$iconify_players()

$fill_grid_3x3(1)

$empty_axes()
$join_axes_3x3()

$fill_matrix(1)
$join_matrix_3x3()
@enduml

@startuml matrix-with-protocols-plural
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 20
skinparam nodesep 40

<style>
  .matrix {
    FontSize: 30;
    FontColor: Grey;
  }
</style>

$iconify_players(2)

$fill_grid_3x3(2)

$empty_axes()
$join_axes_3x3()

$fill_matrix(2)
$join_matrix_3x3()
@enduml

@startuml protocols-with-runtime-agents
!include lib/game.puml!core
!include lib/i18n.puml!en
skinparam ranksep 20
skinparam nodesep 40

$iconify_players(2)

$fill_grid_5x3("run", 2)

$empty_axes()
$join_axes_5x3("hidden")
@enduml

@startuml abstraction-stack
!include lib/game.puml!core
!include lib/i18n.puml!en

<style>
  label {
    FontSize: 30;
    HorizontalAlignment: center;
  }
</style>

label stack [
  <#gainsboro>|= $translate(layer) |=\t     $translate(abstraction, 2) |
  ' |   3 | $translate(player), $translate(characterController), $translate(avatarController) |
  |<r> 2 | $translate(character), $translate(avatar), $translate(story), $translate(narrative) |
  |<r> 2 | $translate(intention), $translate(action), $translate(event), $translate(effect) |
  |<r> 1 | $translate(theme), $translate(arc), $translate(setting), $translate(mechanic) |
]
@enduml
