@startuml multi-player-loops
!include lib/game.puml!core
skinparam ranksep 30
skinparam nodesep 65
scale max 600 width

$fill_grid_3x1("mp")

character -[dashed]d-> "\n\n\nD" player
character -[plain]d-> "B" player
character ~[thickness=1]d~ player
character -[plain]d- "A" player
character -[dashed]d- "C\n\n\n" player

player "\n\n\nW" <-[dashed]d- avatar
player "Y" <-[plain]d- avatar
player ~[thickness=1]d~ avatar
player "Z" -[plain]d- avatar
player "X\n\n\n" -[dashed]d- avatar

$fill_matrix()
$join_matrix_3x1()

$empty_legend()
$join_legend_3x1()
@enduml

@startuml player-action-loop
!include lib/game.puml!core
skinparam ranksep 30
skinparam nodesep 70
scale max 1200 width

$fill_grid_5x1("sp")

master "B" <-[plain]d- character
master ~[thickness=1]d~ character
master "C" -[dashed]d- character

character -[dashed]d-> "D" player
character ~[thickness=1]d~ player
character -[plain]d- "A" player

player "W" <-[dashed]d- avatar
player ~[thickness=1]d~ avatar
player "Z" -[plain]d- avatar

avatar -[plain]d-> "Y" engine
avatar ~[thickness=1]d~ engine
avatar -[dashed]d- "X" engine

$fill_matrix()
$join_matrix_3x1()

$empty_legend()
$join_legend_y()
@enduml

@startuml player-reaction-loop
!include lib/game.puml!core
skinparam ranksep 30
skinparam nodesep 70
scale max 1200 width

$fill_grid_5x1("sp")

master "D" <-[dashed]d- character
master ~[thickness=1]d~ character
master "A" -[plain]d- character

character -[plain]d-> "B" player
character ~[thickness=1]d~ player
character -[dashed]d- "C" player

player "Y" <-[plain]d- avatar
player ~[thickness=1]d~ avatar
player "X" -[dashed]d- avatar

avatar -[dashed]d-> "W" engine
avatar ~[thickness=1]d~ engine
avatar -[plain]d- "Z" engine

$fill_matrix()
$join_matrix_3x1()

$empty_legend()
$join_legend_y()
@enduml
