@startuml player-with-legend-x
!include lib/game.puml!core
skinparam ranksep 100
skinparam nodesep 30

$fill_origin()

$fill_legend_x(plane)
$empty_legend_y()
$join_legend_1x1($x="hidden")
@enduml

@startuml player-with-legend-y
!include lib/game.puml!core
skinparam ranksep 100
skinparam nodesep 10

$fill_origin()

$empty_legend_x()
$fill_legend_y(plane)
$join_legend_1x1($y="hidden")
@enduml

@startuml player-with-legend
!include lib/game.puml!core
skinparam ranksep 120
skinparam nodesep 20

$fill_origin()

$fill_legend()
$join_legend_1x1()
@enduml

@startuml filled-matrix
!include lib/game.puml!core
!include lib/i18n.puml!ru
skinparam ranksep 30
skinparam nodesep 20

$fill_origin()

$empty_grid_3x3()
$join_grid_3x3()

$fill_matrix(2)
$join_matrix_3x3()

$fill_legend()
$join_legend_3x3()
@enduml