@startuml player-dualities
!include lib/player.puml!loop
skinparam ranksep 25
skinparam nodesep 100
$fillLegend()
$hiddenLoop()
@enduml

@startuml player-dualities-matrix
!include lib/player.puml!loop
skinparam ranksep 15
skinparam nodesep 100
$fillLegend()
$hiddenLoop()
$fillMatrix()
@enduml

@startuml player-loop
!include lib/player.puml!loop
skinparam ranksep 60
skinparam nodesep 50
$emptyLegend()
$fillLoop()
@enduml

@startuml player-loop-matrix
!include lib/player.puml!loop
skinparam ranksep 60
skinparam nodesep 50
$emptyLegend()
$fillLoop()
$fillMatrix()
@enduml

@startuml player-loop-full
!include lib/player.puml!loop
skinparam ranksep 40
skinparam nodesep 50
$fillLegend()
$fillLoop()
$fillMatrix()
@enduml