@startuml (id=loop)
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/cog>
!include <tupadr3/font-awesome-5/pen_square>
!include <tupadr3/font-awesome-5/user_alt>
!include <tupadr3/font-awesome-5/user_cog>
!include <tupadr3/font-awesome-5/user_edit>
!include <tupadr3/font-awesome-5/question>
!include <tupadr3/font-awesome-5/question_circle>
!include <tupadr3/font-awesome-5/puzzle_piece>

skinparam defaultTextAlignment center
skinparam defaultFontName Ubuntu Mono
skinparam defaultFontSize 15
scale max 1200 width

left to right direction

<style>
  rectangle {
    FontSize 20
  }
  collections {
    FontSize 20
  }
  label {
    FontSize 16
  }
  .axis {
    FontSize 12
    FontColor DimGrey
  }
  .sth {
  }
  .nth {
    FontSize 12
    FontColor Transparent
  }
  .puzzler {
    FontSize 50
    FontStyle bold
  }
</style>

!procedure $fillPlayer($style=sth)
  label origin <<$style>> [
    <$user_alt>
    игрок
  ]
!endprocedure

!procedure $fillPlayers()
  label origin [
    <$user_alt{scale=0.4}>
    <$user_alt{scale=0.4}>  <$user_alt{scale=0.4}>
    <$user_alt{scale=0.4}>
    игроки
  ]
!endprocedure

!procedure $fillCharacter()
  rectangle character [
    <$pen_square{scale=0.4}><size:8> </size>персонаж
  ]
!endprocedure

!procedure $hideCharacter()
  $fillCharacter()
  hide character
!endprocedure

!procedure $emptyCharacter()
  label character [
  ]
!endprocedure

!procedure $fillCharacters()
  collections character [
    <$pen_square{scale=0.4}><size:8> </size>персонажи
  ]
!endprocedure

!procedure $fillAvatar()
  rectangle avatar [
    <$cog{scale=0.4}><size:8> </size>аватар
  ]
!endprocedure

!procedure $hideAvatar()
  $fillAvatar()
  hide avatar
!endprocedure

!procedure $emptyAvatar()
  label avatar [
  ]
!endprocedure

!procedure $fillAvatars()
  collections avatar [
    <$cog{scale=0.4}><size:8> </size>аватары
  ]
!endprocedure

!procedure $fillHorizontal3()
  $fillCharacters()
  $fillPlayers()
  $fillAvatars()
!endprocedure

!procedure $fillLegend()
  $fillLegendX()
  $fillLegendY()
!endprocedure

!procedure $fillLegendX($style=axis)
  label leftmost <<$style>> [
    н
    а
    р
    р
    а
    т
    и
    в
  ]
  label rightmost <<$style>> [
    г
    е
    й
    м
    п
    л
    е
    й
  ]
!endprocedure

!procedure $hideLegendX()
  $fillLegendX()
  hide leftmost
  hide rightmost
!endprocedure

!procedure $fillLegendY($style=axis)
  label highest <<$style>> [
    р а ц и о
  ]
  label lowest <<$style>> [
    э м о ц и о
  ]
!endprocedure

!procedure $hideLegendY()
  $fillLegendY()
  hide highest
  hide lowest
!endprocedure

!procedure $emptyLegend()
  $emptyLegendX()
  $emptyLegendY()
!endprocedure

!procedure $emptyLegendX()
  label leftmost <<axis>> [
  ]
  label rightmost <<axis>> [
  ]
!endprocedure

!procedure $emptyLegendY()
  label highest <<axis>> [
  ]
  label lowest <<axis>> [
  ]
!endprocedure

!procedure $joinLegend1($x, $y="hidden")
  leftmost ~[$x]d~ origin
  origin ~[$x]d~ rightmost
  highest ~[$y]r~ origin
  origin ~[$y]r~ lowest
!endprocedure

!procedure $joinLegend3($x, $y="hidden")
  leftmost ~[$x]d~ character
  avatar ~[$x]d~ rightmost
  highest ~[$y]r~ origin
  origin ~[$y]r~ lowest
!endprocedure

!procedure $joinLegend5($x, $y="hidden")
  leftmost ~[$x]d~ master
  engine ~[$x]d~ rightmost
  highest ~[$y]r~ origin
  origin ~[$y]r~ lowest
!endprocedure

!procedure $fillPlot()
  label plot [
    сюжет
  ]
!endprocedure

!procedure $fillTheme()
  label theme [
    тема
  ]
!endprocedure

!procedure $fillNarrativeMatrix()
  $fillPlot()
  $fillTheme()
!endprocedure

!procedure $fillMasterMatrix()
  label plot [
    сюжет
  ]
  label theme [
    тема
  ]
  plot -[hidden]r- character
  character -[hidden]r- theme
!endprocedure

!procedure $fillMechanics()
  label mechanics [
    механика
  ]
!endprocedure

!procedure $fillSetting()
  label setting [
    сеттинг
  ]
!endprocedure

!procedure $fillGameplayMatrix()
  $fillMechanics()
  $fillSetting()
!endprocedure

!procedure $fillRatioMatrix()
  $fillPlot()
  $fillMechanics()
!endprocedure

!procedure $fillEmotioMatrix()
  $fillTheme()
  $fillSetting()
!endprocedure

!procedure $puzzleMatrix()
  $fillPuzzle(plot)
  $fillPuzzle(mechanics)
  $fillPuzzle(setting)
  $fillPuzzle(theme)
!endprocedure

!procedure $joinMatrix()
  plot -[hidden]r- character
  character -[hidden]r- theme
  mechanics -[hidden]r- avatar
  avatar -[hidden]r- setting
!endprocedure

!procedure $fillEngineMatrix()
  label mechanics [
    механика
  ]
  label setting [
    сеттинг
  ]
  mechanics -[hidden]r- avatar
  avatar -[hidden]r- setting
!endprocedure

!procedure $fillGameMatrix()
  $fillMasterMatrix()
  $fillEngineMatrix()
!endprocedure

!procedure $fillGameLoop()
  $fillCharacters()
  $fillAvatars()

  FA5_USER_EDIT(master, "мастер ", label)

  character -u-> master
  master ~[thickness=1]d~ character
  master -d-> character
  
  character -d-> origin
  character ~[thickness=1]d~ origin
  origin -u-> character

  FA5_USER_COG(engine, "движок ", label)

  avatar -u-> origin
  origin ~[thickness=1]d~ avatar
  origin -d-> avatar
  
  avatar -d-> engine
  avatar ~[thickness=1]d~ engine
  engine -u-> avatar

  $fillGameGrid()
!endprocedure

!procedure $fillMaster()
  FA5_USER_EDIT(master, "мастер ", label)
!endprocedure

!procedure $emptyMaster()
  label master [
  ]
!endprocedure

!procedure $fillEngine()
  FA5_USER_COG(engine, "движок ", label)
!endprocedure

!procedure $fillPuzzle($key)
  label $key <<puzzler>> [
    ?
  ]
!endprocedure

!procedure $emptyEngine()
  label engine [
  ]
!endprocedure

!procedure $emptyGameLoop()
  label character [
  ]
  label avatar [
  ]

  leftmost ~[thickness=1]d~ character
  character ~[thickness=1]d~ origin
  origin ~[thickness=1]d~ avatar
  avatar ~[thickness=1]d~ rightmost

  $fillVertical()
!endprocedure

!procedure $fillGameGrid()
  $fillHorizontal()
  $fillVertical()
!endprocedure

!procedure $fillHorizontal()
  leftmost ~[thickness=1]d~ master
  engine ~[thickness=1]d~ rightmost
!endprocedure

!procedure $joinGrid3($mode)
  character ~[$mode]d~ origin
  origin ~[$mode]d~ avatar
!endprocedure

!procedure $joinGrid5($mode)
  master ~[$mode]d~ character
  $joinGrid3($mode)
  avatar ~[$mode]d~ engine
!endprocedure

!procedure $fillVertical()
  highest ~[thickness=1]r~ origin: \n
  origin ~[thickness=1]r~ lowest: \n
!endprocedure

!procedure $hiddenGameGrid()
  leftmost ~[hidden]d~ origin
  origin ~[hidden]d~ rightmost
!endprocedure

!procedure $fillGameStruct($count)
  !if ($count == 1)
    $fillCharacter()
    $fillPlayer()
    $fillAvatar()
  !else
    $fillCharacters()
    $fillPlayers()
    $fillAvatars()
  !endif

  leftmost ~[hidden]d~ master
  master ~[hidden]d~ character
  character ~[hidden]d~ origin
  origin ~[hidden]d~ avatar
  avatar ~[hidden]d~ engine
  engine ~[hidden]d~ rightmost
!endprocedure

!$debug = 0
!if ($debug)
  $fillPuzzle(foo)
!endif
@enduml
