@startuml (id=core)
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/cog>
!include <tupadr3/font-awesome-5/pen_square>
!include <tupadr3/font-awesome-5/user_alt>
!include <tupadr3/font-awesome-5/user_cog>
!include <tupadr3/font-awesome-5/user_edit>
!include <tupadr3/font-awesome-5/question>
!include <tupadr3/font-awesome-5/question_circle>
!include <tupadr3/font-awesome-5/puzzle_piece>

skinparam defaultTextAlignment center
skinparam defaultFontName Ubuntu Mono
skinparam defaultFontSize 15
scale max 600 width

left to right direction

<style>
  rectangle {
    FontSize 20
  }
  collections {
    FontSize 20
  }
  label {
    FontSize 16
  }
  .axis {
    FontSize 12
    FontColor DimGrey
  }
  .sth {
  }
  .nth {
    ' FontSize 12
    FontColor Transparent
  }
  .puzzler {
    FontSize 40
    FontStyle bold
  }
</style>

!procedure $fill_player($style=sth)
  label origin <<$style>> [
    <$user_alt{scale=0.9}>
    игрок
  ]
!endprocedure

!procedure $fill_players()
  label origin [
    <$user_alt{scale=0.4}>
    <$user_alt{scale=0.4}>  <$user_alt{scale=0.4}>
    <$user_alt{scale=0.4}>
    игроки
  ]
!endprocedure

!procedure $empty_character()
  label character [
  ]
!endprocedure

!procedure $fill_character()
  rectangle character [
    <$pen_square{scale=0.4}><size:8> </size>персонаж
  ]
!endprocedure

!procedure $fill_characters()
  collections character [
    <$pen_square{scale=0.4}><size:8> </size>персонажи
  ]
!endprocedure

!procedure $empty_avatar()
  label avatar [
  ]
!endprocedure

!procedure $puzzle_protocol($id)
  rectangle $id #line.dotted;back:transparent [
    <U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>
  ]
!endprocedure

!procedure $fill_avatar()
  rectangle avatar [
    <$cog{scale=0.4}><size:8> </size>аватар
  ]
!endprocedure

!procedure $fill_avatars()
  collections avatar [
    <$cog{scale=0.4}><size:8> </size>аватары
  ]
!endprocedure

!procedure $empty_master()
  label master [
  ]
!endprocedure

!procedure $fill_master()
  label master [
    <$user_edit{scale=0.9}>
    мастер
  ]
!endprocedure

!procedure $empty_engine()
  label engine [
  ]
!endprocedure

!procedure $fill_engine()
  label engine [
    <$user_cog{scale=0.9}>
    движок
  ]
!endprocedure

!procedure $puzzle_actor($id)
  label $id <<puzzler>> [
     ?
  ]
!endprocedure

!procedure $fill_legend()
  $fill_legend_x()
  $fill_legend_y()
!endprocedure

!procedure $fill_legend_x($style=axis)
  label leftmost <<$style>> [
    н
    а
    р
    р
    а
    т
    и
    в
  ]
  label rightmost <<$style>> [
    г
    е
    й
    м
    п
    л
    е
    й
  ]
!endprocedure

!procedure $fill_legend_y($style=axis)
  label highest <<$style>> [
    р а ц и о
  ]
  label lowest <<$style>> [
    э м о ц и о
  ]
!endprocedure

!procedure $empty_legend()
  $empty_legend_x()
  $empty_legend_y()
!endprocedure

!procedure $empty_legend_x()
  label leftmost <<axis>> [
  ]
  label rightmost <<axis>> [
  ]
!endprocedure

!procedure $empty_legend_y()
  label highest <<axis>> [
  ]
  label lowest <<axis>> [
  ]
!endprocedure

!procedure $join_legend_1x1($x, $y="hidden")
  leftmost ~[$x]d~ origin
  origin ~[$x]d~ rightmost
  highest ~[$y]r~ origin
  origin ~[$y]r~ lowest
!endprocedure

!procedure $join_legend_3x1($x, $y="hidden")
  leftmost ~[$x]d~ character
  avatar ~[$x]d~ rightmost
  highest ~[$y]r~ origin
  origin ~[$y]r~ lowest
!endprocedure

!procedure $join_legend_3x3($x, $y="hidden")
  leftmost ~[$x]d~ character
  avatar ~[$x]d~ rightmost
  highest ~[$y]r~ upper
  lower ~[$y]r~ lowest
!endprocedure

!procedure $join_legend_5x1($x, $y="hidden")
  leftmost ~[$x]d~ master
  engine ~[$x]d~ rightmost
  highest ~[$y]r~ origin
  origin ~[$y]r~ lowest
!endprocedure

!procedure $join_legend_5x3($x, $y="hidden")
  leftmost ~[$x]d~ master
  engine ~[$x]d~ rightmost
  highest ~[$y]r~ upper
  lower ~[$y]r~ lowest
!endprocedure

!procedure $fill_plot()
  label plot [
    ""  сюжет  ""
  ]
!endprocedure

!procedure $fill_theme()
  label theme [
    ""  тема  ""
  ]
!endprocedure

!procedure $fillMasterMatrix()
  label plot [
    ""сюжет""
  ]
  label theme [
    ""тема""
  ]
  plot -[hidden]r- character
  character -[hidden]r- theme
!endprocedure

!procedure $fill_mechanics()
  label mechanics [
    ""механика""
  ]
!endprocedure

!procedure $fill_setting()
  label setting [
    ""сеттинг""
  ]
!endprocedure

!procedure $fill_matrix()
  $fill_plot()
  $fill_theme()
  $fill_setting()
  $fill_mechanics()
!endprocedure

!procedure $puzzle_matrix()
  $puzzle_actor(plot)
  $puzzle_actor(mechanics)
  $puzzle_actor(setting)
  $puzzle_actor(theme)
!endprocedure

!procedure $join_matrix_3x1()
  plot -[hidden]r- character
  character -[hidden]r- theme
  mechanics -[hidden]r- avatar
  avatar -[hidden]r- setting
!endprocedure

!procedure $join_matrix_3x3()
  plot -[hidden]d- upper
  upper -[hidden]d- mechanics
  theme -[hidden]d- lower
  lower -[hidden]d- setting
!endprocedure

!procedure $fillEngineMatrix()
  label mechanics [
    механика
  ]
  label setting [
    сеттинг
  ]
  mechanics -[hidden]r- avatar
  avatar -[hidden]r- setting
!endprocedure

!procedure $fillGameMatrix()
  $fillMasterMatrix()
  $fillEngineMatrix()
!endprocedure

!procedure $fillGameLoop()
  $fill_characters()
  $fill_avatars()

  FA5_USER_EDIT(master, "мастер ", label)

  character -u-> master
  master ~[thickness=1]d~ character
  master -d-> character
  
  character -d-> origin
  character ~[thickness=1]d~ origin
  origin -u-> character

  FA5_USER_COG(engine, "движок ", label)

  avatar -u-> origin
  origin ~[thickness=1]d~ avatar
  origin -d-> avatar
  
  avatar -d-> engine
  avatar ~[thickness=1]d~ engine
  engine -u-> avatar

  $fillGameGrid()
!endprocedure

!procedure $emptyGameLoop()
  label character [
  ]
  label avatar [
  ]

  leftmost ~[thickness=1]d~ character
  character ~[thickness=1]d~ origin
  origin ~[thickness=1]d~ avatar
  avatar ~[thickness=1]d~ rightmost

  $fillVertical()
!endprocedure

!procedure $fillGameGrid()
  $fillHorizontal()
  $fillVertical()
!endprocedure

!procedure $fillHorizontal()
  leftmost ~[thickness=1]d~ master
  engine ~[thickness=1]d~ rightmost
!endprocedure

!procedure $fillVertical()
  highest ~[thickness=1]r~ origin: \n
  origin ~[thickness=1]r~ lowest: \n
!endprocedure

!procedure $empty_grid_1x3()
  label upper [
  ]
  $fill_player()
  label lower [
  ]
!endprocedure

!procedure $empty_grid_3x3()
  $empty_character()
  $fill_player()
  $empty_avatar()
  label upper [
  ]
  label lower [
  ]
!endprocedure

!procedure $empty_grid_3x1()
  $empty_character()
  $fill_player()
  $empty_avatar()
!endprocedure

!procedure $fill_grid_3x1($mode="sp")
  ' sp stand for single player
  !if ($mode=="sp")
    $fill_character()
    $fill_player()
    $fill_avatar()
  !else
    $fill_characters()
    $fill_players()
    $fill_avatars()
  !endif
!endprocedure

!procedure $join_grid_3x1($mode)
  character ~[$mode]d~ origin
  origin ~[$mode]d~ avatar
!endprocedure

!procedure $fill_grid_5x1($mode="sp")
  $fill_master()
  $fill_grid_3x1($mode)
  $fill_engine()
!endprocedure

!procedure $join_grid_5x1($mode)
  master ~[$mode]d~ character
  $join_grid_3x1($mode)
  avatar ~[$mode]d~ engine
!endprocedure

!procedure $join_grid_1x3($mode)
  upper ~[$mode]r~ origin
  origin ~[$mode]r~ lower
!endprocedure

!procedure $join_grid_3x3($mode)
  $join_grid_3x1($mode)
  $join_grid_1x3($mode)
!endprocedure

!procedure $join_grid_5x3($mode)
  $join_grid_5x1($mode)
  $join_grid_1x3($mode)
!endprocedure

!$debug = 0
!if ($debug)
skinparam ranksep 20
skinparam nodesep 20
$fill_grid_5x1()
$empty_grid_1x3()
$join_grid_5x3("thickness=1")

$fill_matrix()
$join_matrix_3x3()

$fill_legend()
$join_legend_5x3("thickness=1", "thickness=1")
!endif
@enduml
