@startuml (id=core)
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/cog>
!include <tupadr3/font-awesome-5/pen_square>
!include <tupadr3/font-awesome-5/user_alt>
!include <tupadr3/font-awesome-5/user_cog>
!include <tupadr3/font-awesome-5/user_edit>
!include <tupadr3/font-awesome-5/question>
!include <tupadr3/font-awesome-5/question_circle>
!include <tupadr3/font-awesome-5/puzzle_piece>

skinparam defaultTextAlignment center
skinparam defaultFontName Ubuntu Mono
skinparam defaultFontSize 15
scale max 600 width

left to right direction

<style>
  rectangle {
    FontSize 20
  }
  collections {
    FontSize 20
  }
  label {
    FontSize 16
  }
  .axis {
    FontSize 12
    FontColor DimGrey
  }
  .sth {
  }
  .nth {
    ' FontSize 12
    FontColor Transparent
  }
  .puzzler {
    FontSize 40
    FontStyle bold
  }
</style>

!procedure $fill_player($mode="sp", $style=sth)
  !if ($mode=="sp")
    label player <<$style>> [
      <$user_alt{scale=0.9}>
      игрок
    ]
  !else
    label player [
      <$user_alt{scale=0.4}>
      <$user_alt{scale=0.4}>  <$user_alt{scale=0.4}>
      <$user_alt{scale=0.4}>
      игроки
    ]
  !endif
!endprocedure

!procedure $empty_character()
  label character [
  ]
!endprocedure

!procedure $fill_character($mode="sp")
  !if ($mode=="sp")
    rectangle character [
      <$pen_square{scale=0.4}><size:8> </size>персонаж
    ]
  !else
    collections character [
      <$pen_square{scale=0.4}><size:8> </size>персонажи
    ]
  !endif
!endprocedure

!procedure $empty_avatar()
  label avatar [
  ]
!endprocedure

!procedure $fill_avatar($mode="sp")
  !if ($mode=="sp")
    rectangle avatar [
      <$cog{scale=0.4}><size:8> </size>аватар
    ]
  !else
    collections avatar [
      <$cog{scale=0.4}><size:8> </size>аватары
    ]
  !endif
!endprocedure

!procedure $empty_master()
  label master [
  ]
!endprocedure

!procedure $fill_master()
  label master [
    <$user_edit{scale=0.9}>
    мастер
  ]
!endprocedure

!procedure $empty_engine()
  label engine [
  ]
!endprocedure

!procedure $fill_engine()
  label engine [
    <$user_cog{scale=0.9}>
    движок
  ]
!endprocedure

!procedure $puzzle_actor($id)
  label $id <<puzzler>> [
     ?
  ]
!endprocedure

!procedure $puzzle_protocol($id)
  rectangle $id #line.dotted;back:transparent [
    <U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>
  ]
!endprocedure

!procedure $fill_legend()
  $fill_legend_x()
  $fill_legend_y()
!endprocedure

!procedure $fill_legend_x($style=axis)
  label leftmost <<$style>> [
    н
    а
    р
    р
    а
    т
    и
    в
  ]
  label rightmost <<$style>> [
    г
    е
    й
    м
    п
    л
    е
    й
  ]
!endprocedure

!procedure $fill_legend_y($style=axis)
  label highest <<$style>> [
    р а ц и о
  ]
  label lowest <<$style>> [
    э м о ц и о
  ]
!endprocedure

!procedure $empty_legend()
  $empty_legend_x()
  $empty_legend_y()
!endprocedure

!procedure $empty_legend_x()
  label leftmost <<axis>> [
  ]
  label rightmost <<axis>> [
  ]
!endprocedure

!procedure $empty_legend_y()
  label highest <<axis>> [
  ]
  label lowest <<axis>> [
  ]
!endprocedure

!procedure $join_legend_1x1($x, $y="hidden")
  leftmost ~[$x]d~ player
  player ~[$x]d~ rightmost
  highest ~[$y]r~ player
  player ~[$y]r~ lowest
!endprocedure

!procedure $join_legend_3x1($x, $y="hidden")
  leftmost ~[$x]d~ character
  avatar ~[$x]d~ rightmost
  highest ~[$y]r~ player
  player ~[$y]r~ lowest
!endprocedure

!procedure $join_legend_3x3($x, $y="hidden")
  leftmost ~[$x]d~ character
  avatar ~[$x]d~ rightmost
  highest ~[$y]r~ upper
  lower ~[$y]r~ lowest
!endprocedure

!procedure $join_legend_5x1($x, $y="hidden")
  leftmost ~[$x]d~ master
  engine ~[$x]d~ rightmost
  highest ~[$y]r~ player
  player ~[$y]r~ lowest
!endprocedure

!procedure $join_legend_5x3($x, $y="hidden")
  leftmost ~[$x]d~ master
  engine ~[$x]d~ rightmost
  highest ~[$y]r~ upper
  lower ~[$y]r~ lowest
!endprocedure

!procedure $fill_plot()
  label plot [
    ""  сюжет  ""
  ]
!endprocedure

!procedure $fill_theme()
  label theme [
    ""  тема  ""
  ]
!endprocedure

!procedure $fill_mechanics()
  label mechanics [
    ""механика""
  ]
!endprocedure

!procedure $fill_setting()
  label setting [
    ""сеттинг""
  ]
!endprocedure

!procedure $fill_matrix()
  $fill_plot()
  $fill_theme()
  $fill_setting()
  $fill_mechanics()
!endprocedure

!procedure $puzzle_matrix()
  $puzzle_actor(plot)
  $puzzle_actor(mechanics)
  $puzzle_actor(setting)
  $puzzle_actor(theme)
!endprocedure

!procedure $join_matrix_3x1()
  plot -[hidden]r- character
  character -[hidden]r- theme
  mechanics -[hidden]r- avatar
  avatar -[hidden]r- setting
!endprocedure

!procedure $join_matrix_3x3()
  plot -[hidden]d- upper
  upper -[hidden]d- mechanics
  theme -[hidden]d- lower
  lower -[hidden]d- setting
!endprocedure

!procedure $empty_grid_1x3()
  label upper [
  ]
  $fill_player()
  label lower [
  ]
!endprocedure

!procedure $empty_grid_3x1()
  $empty_character()
  $fill_player()
  $empty_avatar()
!endprocedure

!procedure $empty_grid_3x3()
  $empty_character()
  $fill_player()
  $empty_avatar()
  label upper [
  ]
  label lower [
  ]
!endprocedure

!procedure $fill_grid_3x1($mode="sp")
  $fill_character($mode)
  $fill_player($mode)
  $fill_avatar($mode)
!endprocedure

!procedure $fill_grid_5x1($mode="sp")
  $fill_master()
  $fill_grid_3x1($mode)
  $fill_engine()
!endprocedure

!procedure $fill_narrative($mode="sp")
  $fill_master()
  $fill_character($mode)
  $fill_player($mode)
!endprocedure

!procedure $fill_gameplay($mode="sp")
  $fill_player($mode)
  $fill_avatar($mode)
  $fill_engine()
!endprocedure

!procedure $join_grid_1x3($mode)
  upper ~[$mode]r~ player
  player ~[$mode]r~ lower
!endprocedure

!procedure $join_grid_3x1($mode)
  character ~[$mode]d~ player
  player ~[$mode]d~ avatar
!endprocedure

!procedure $join_grid_5x1($mode)
  $join_narrative_5x1($mode)
  $join_gameplay_5x1($mode)
!endprocedure

!procedure $join_grid_3x3($mode)
  $join_grid_3x1($mode)
  $join_grid_1x3($mode)
!endprocedure

!procedure $join_grid_5x3($mode)
  $join_grid_5x1($mode)
  $join_grid_1x3($mode)
!endprocedure

!procedure $join_narrative_5x1($mode)
  master ~[$mode]d~ character
  character ~[$mode]d~ player
!endprocedure

!procedure $join_gameplay_5x1($mode)
  player ~[$mode]d~ avatar
  avatar ~[$mode]d~ engine
!endprocedure

!procedure $join_actors_5x1($mode="thickness=1")
  master ~[$mode]d~ character
  avatar ~[$mode]d~ engine
!endprocedure

!procedure $loop_character($mode="thickness=1")
  character -d-> player
  character ~[$mode]d~ player
  character <-d- player
!endprocedure

!procedure $loop_avatar($mode="thickness=1")
  player <-d- avatar
  player ~[$mode]d~ avatar
  player -d-> avatar
!endprocedure

!procedure $loop_master($mode="thickness=1")
  master <-d- character
  master ~[$mode]d~ character
  master -d-> character
!endprocedure

!procedure $loop_engine($mode="thickness=1")
  avatar -d-> engine
  avatar ~[$mode]d~ engine
  avatar <-d- engine
!endprocedure

!procedure $loop_narrative($mode="thickness=1")
  $loop_master($mode)
  $loop_character($mode)
!endprocedure

!procedure $loop_gameplay($mode="thickness=1")
  $loop_avatar($mode)
  $loop_engine($mode)
!endprocedure

!$debug = 0
!if ($debug)
skinparam ranksep 20
skinparam nodesep 20
$fill_grid_5x1()
$empty_grid_1x3()
$join_grid_5x3("thickness=1")

$fill_matrix()
$join_matrix_3x3()

$fill_legend()
$join_legend_5x3("thickness=1", "thickness=1")
!endif
@enduml
