@startuml (id=core)
!function $translate($key, $count=1)
  !if ($count==1)
    !return $locale[$key].one
  !else
    !return $locale[$key].many
  !endif
!endfunction
@enduml

@startuml (id=ru)
!$locale = {
  "as": {
    "one": "как"
  },
  "player": {
    "one": "игрок",
    "many": "игроки"
  },
  "master": {
    "one": "мастер"
  },
  "engine": {
    "one": "движок"
  },
  "character": {
    "one": "персонаж",
    "many": "персонажы"
  },
  "avatar": {
    "one": "аватар",
    "many": "аватары"
  },
  "gamelang": {
    "one": "геймлэнг"
  },
  "gameplay": {
    "one": "геймплей"
  },
  "gameloop": {
    "one": "геймлуп"
  },
  "gamefeel": {
    "one": "геймфил"
  },
  "intention": {
    "one": "н а м е р е н и е"
  },
  "action": {
    "one": "д е й с т в и е"
  },
  "plot": {
    "one": "сюжет"
  },
  "narrative": {
    "one": "нарратив"
  },
  "arc": {
    "one": "арка",
    "many": "арки"
  },
  "theme": {
    "one": "тема",
    "many": "темы"
  },
  "mechanic": {
    "one": "механика",
    "many": "механики"
  },
  "setting": {
    "one": "сеттинг",
    "many": "сеттинги"
  }
}
@enduml

@startuml (id=en)
!$locale = {
  "as": {
    "one": "as"
  },
  "player": {
    "one": "player",
    "many": "players"
  },
  "master": {
    "one": "master",
    "many": "masters"
  },
  "engine": {
    "one": "engine",
    "many": "engines"
  },
  "character": {
    "one": "character",
    "many": "characters"
  },
  "character2": {
    "one": "c h a r a c t e r",
    "many": "c h a r a c t e r s"
  },
  "avatar": {
    "one": "avatar",
    "many": "avatars"
  },
  "avatar2": {
    "one": "a v a t a r",
    "many": "a v a t a r s"
  },
  "gamelang": {
    ' "one": "g\na\nm\ne\nl\na\nn\ng"
    "one": "g a m e l a n g"
    ' "one": "gamelang"
  },
  "gamelang2": {
    "one": "gamelang"
  },
  "gameplay": {
    ' "one": "g\na\nm\ne\np\nl\na\ny"
    "one": "g a m e p l a y"
    ' "one": "gameplay"
  },
  "gameplay2": {
    "one": "gameplay"
  },
  "gameloop": {
    "one": "g\na\nm\ne\nl\no\no\np"
    ' "one": "g a m e l o o p"
    ' "one": "gameloop"
  },
  "gameloop2": {
    "one": "gameloop"
  },
  "gamefeel": {
    "one": "g\na\nm\ne\nf\ne\ne\nl"
    ' "one": "g a m e f e e l"
    ' "one": "gamefeel"
  },
  "gamefeel2": {
    "one": "gamefeel"
  },
  "intention": {
    ' "one": "i n t e n t i o n a l"
    "one": "i\nn\nt\ne\nn\nt\ni\no\nn"
  },
  "action": {
    ' "one": "o p e r a t i o n a l"
    "one": "a\nc\nt\ni\no\nn"
  },
  "plot": {
    ' "one": "p\nl\no\nt"
    ' "one": "p l o t"
    "one": "plot",
    "many": "plots"
  },
  "story": {
    "one": "story",
    "many": "stories"
  },
  "narrative": {
    ' "one": "n\na\nr\nr\na\nt\ni\nv\ne"
    "one": "narrative",
    "many": "narratives"
  },
  "arc": {
    "one": "arc",
    "many": "arcs"
  },
  "theme": {
    "one": "theme",
    "many": "themes"
  },
  "mechanic": {
    "one": "mechanic",
    "many": "mechanics"
  },
  "setting": {
    "one": "setting",
    "many": "settings"
  }
}
@enduml