@startuml (id=core)
!function $translate($key, $count=1)
  !if ($count==1)
    !return $locale[$key].one
  !else
    !return $locale[$key].many
  !endif
!endfunction
@enduml

@startuml (id=ru)
!$locale = {
  "player": {
    "one": "игрок",
    "many": "игроки"
  },
  "master": {
    "one": "мастер"
  },
  "engine": {
    "one": "движок"
  },
  "character": {
    "one": "персонаж",
    "many": "персонажы"
  },
  "avatar": {
    "one": "аватар",
    "many": "аватары"
  },
  "gametalk": {
    "one": "и\nс\nт\nо\nр\nи\nя"
    ' "one": "к\nу\nл\nс\nт\nо\nр\nи"
  },
  "gameplay": {
    "one": "г\nе\nй\nм\nп\nл\nе\nй"
  },
  "ratio": {
    "one": "р а ц и о"
  },
  "emotio": {
    "one": "э м о ц и о"
  },
  "arc": {
    "one": "арка",
    "many": "арки"
  },
  "theme": {
    "one": "тема",
    "many": "темы"
  },
  "mechanic": {
    "one": "механика",
    "many": "механики"
  },
  "setting": {
    "one": "сеттинг",
    "many": "сеттинги"
  }
}
@enduml

@startuml (id=en)
!$locale = {
  "player": {
    "one": "player",
    "many": "players"
  },
  "master": {
    "one": "gamemaster",
    "many": "gamemasters"
  },
  "engine": {
    "one": "engine",
    "many": "engines"
  },
  "character": {
    "one": "character",
    "many": "characters"
  },
  "character2": {
    "one": "c h a r a c t e r",
    "many": "c h a r a c t e r s"
  },
  "avatar": {
    "one": "avatar",
    "many": "avatars"
  },
  "avatar2": {
    "one": "a v a t a r",
    "many": "a v a t a r s"
  },
  "gametalk": {
    ' "one": "g\na\nm\ne\nl\na\nn\ng"
    ' "one": "g a m e l a n g"
    "one": "g a m e t a l k"
    ' "one": "g\nr\na\nm\nm\na\nr"
    ' "one": "l\ne\nx\ni\nc\no\nn"
    ' "one": "s\ne\nm\na\nn\nt\ni\nc\ns"
  },
  "gameplay": {
    ' "one": "g\na\nm\ne\np\nl\na\ny"
    "one": "g a m e p l a y"
  },
  "plot": {
    ' "one": "p\nl\no\nt"
    "one": "plot"
  },
  "narrative": {
    ' "one": "n\na\nr\nr\na\nt\ni\nv\ne"
    "one": "narrative"
  },
  "ratio": {
    ' "one": "r a t i o"
    ' "one": "rational"
    ' "one": "r a t i o n a l"
    "one": "r\na\nt\ni\no\nn\na\nl"
  },
  "emotio": {
    ' "one": "e m o t i o"
    ' "one": "emotional"
    ' "one": "e m o t i o n a l"
    "one": "e\nm\no\nt\ni\no\nn\na\nl"
  },
  "arc": {
    "one": "arc",
    "many": "arcs"
  },
  "theme": {
    "one": "theme",
    "many": "themes"
  },
  "mechanic": {
    "one": "mechanic",
    "many": "mechanics"
  },
  "setting": {
    "one": "setting",
    "many": "settings"
  }
}
@enduml